Repository ashu96902/Hacktoberfest--2021, pull requests merged in 2021-10, with the labels that each got.

#11 Update reverse.py
  reverse.py
Labels: Hacktoberfest, hacktoberfest-accepted

#12 Update swap.py
  swap.py
Labels: Hacktoberfest2021, hacktoberfest-accepted

#13 Update list.py
  list.py
Labels: Hacktoberfest2021, hacktoberfest-accepted

#14 Update reverse_array.py
  reverse_array.py
Labels: Hacktoberfest2021, hacktoberfest-accepted

#15 Update reverse.py
  reverse.py
Labels: hacktoberfest-accepted

#16 Create Sumoflist.py
  Sumoflist.py
Labels: Hacktoberfest, hacktoberfest-accepted

#18 Quick Sort using python added
  Merge_Sort.py
  Quick_Sort.py
Labels: hacktoberfest-accepted

#17 Added a calcuator
  Calculator.py
Labels: hacktoberfest-accepted

#20 Update Quick_Sort.py
  Quick_Sort.py
Labels: hacktoberfest-accepted

#23 Update reverse_array.py
  reverse_array.py
Labels: hacktoberfest-accepted

#22 Update invisible code
  invisible code
Labels: hacktoberfest-accepted

#21 Update Calculator.py
  Calculator.py
Labels: hacktoberfest-accepted

#19 add heap sort
  Heapsort.py
Labels: hacktoberfest-accepted

#27 Update Heapsort.py
  Heapsort.py
Labels: hacktoberfest-accepted

#26 Update invisible code
  invisible code
Labels: hacktoberfest-accepted

#25 Update list.py
  list.py
Labels: hacktoberfest-accepted

#24 Update Dice roll simulator
  Dice roll simulator
Labels: hacktoberfest-accepted

#28 Create weather_forecast.py
  weather_forecast.py
Labels: hacktoberfest-accepted

#31 Create Dfs Bfs.py
  Dfs Bfs.py
Labels: hacktoberfest-accepted

#30 Create keylogger.py
  keylogger.py
Labels: hacktoberfest-accepted

#29 Create q1.java
  q1.java
Labels: hacktoberfest-accepted
